### ISSUE TITLE
crash on toon gear report

### ISSUE THREAD

**Issue by codeshell** [swgoh-tools/swgoh-guild-management#10]
explode() expects parameter 2 to be string, null given {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): explode() expects parameter 2 to be string, null given at /.../app/Authorizable.php:54)
[stacktrace]
#0 /.../app/Authorizable.php(54): explode('.', NULL)
#1 /.../app/Authorizable.php(38): App\\Http\\Controllers\\PlayerController->getAbility('gear')
#2 /.../vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): App\\Http\\Controllers\\PlayerController->callAction('gear', Array)
#3 /.../vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\PlayerController), 'gear')

**Comment by codeshell** [comment]
auth check needs a route name
